### ISSUE TITLE
UCS 5

### ISSUE THREAD

**Issue by codedmind** [univention/cool-solutions#5]
Hello,

Any prediction when it will be avaible for UCS 5?

Any way to know what the issues (if any) if disable cool solutions repo and upgrade to UCS5 ?

Thanks

**Comment by adf-patrickha** [comment]
Taking this up again, as the missing univention-usercert feature in version 5 prevents us from updating. AFAICT there are already a lot related changes in the ucs5.0 branch. Is this already in a working state? Will this be merged and published as packages soon?

**Comment by spaceone** [comment]
A product fix is required which is currently done in https://forge.univention.org/bugzilla/show_bug.cgi?id=54987.
After this the cool solution must be adapted to use the new product features.

**Comment by altesockensuppe** [comment]
> A product fix is required which is currently done in https://forge.univention.org/bugzilla/show_bug.cgi?id=54987. After this the cool solution must be adapted to use the new product features.

@spaceone Do you have an idea when the changes are in production? We would very much like to upgrade our infrastructure to UCS 5.

**Comment by Flunkyball** [comment]
Hurra, the underlying problem seems to be fixed and has been released 8 days ago: [https://errata.software-univention.de/#/?erratum=5.0x456](url)

@spaceone 
Any idea when the cool solution adaptation can be ready ?

**Comment by admirableadmin** [comment]
univention-usercert was updated for UCS 5 in January/February this year, see
https://help.univention.com/t/cool-solution-creation-and-management-of-user-and-windows-certificates/11782

so I will close this issue here.
