### ISSUE TITLE
SAN or DNS names in generated certificates

### ISSUE THREAD

**Issue by RaZer0r** [univention/cool-solutions#6]
Hi,

I'm looking to add the FQDN into the certificate as an SAN or DNS field, is this possible?

With kind regards,

Rein

**Comment by admirableadmin** [comment]
I am not sure if i understand the request correctly, probably it is about univention-usercert.
Feel free to add this functionality and start a pull request, underlining your use case you want to address by this.
You can have a look at our forum if there are questions: https://help.univention.com/
For sure its not an issue, so I will close it here.
